[package]
name = "qmk-keymap"
version = "0.1.0"

[lib]
name = "keymap"
crate-type = ["staticlib"]
path = "rustsrc/lib.rs"

[dependencies]
cty = "0.2"
paste = "0.1"

[build-dependencies]
bindgen = "0.*"
